### PR TITLE
Always reject the download promise with a `downloadException`

### PR DESCRIPTION
**Pull request by micthiesen**
It is useful to always reject a promise with an `Error` (superclass of `downloadException`). Using an `Error` ensures you have access to stack traces which can help with debugging: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Promise/reject#description

In our case, using an `Error` as the reject reason would help give Sentry
better error information: https://github.com/getsentry/sentry-javascript/issues/2546#issuecomment-645357265

### CODE REVIEW

**Comment by micthiesen** [comment]
@AleeeKoi this would help my team debug some errors. Let me know if I've done anything wrong or if you'd like changes!

**Comment by micthiesen** [comment]
Also I tested these changes in our project (various successful downloads and different types of failures, including: bad status codes, network errors, and timeouts) and it worked fine.

**Comment by AleeeKoi** [comment]
Hi @micthiesen , you are right! 
PR seem fine, I will merge it asap. :)
Thank you

**Comment by micthiesen** [comment]
Thanks 🙂

**Comment by AleeeKoi** [comment]
Merged!

image

**Comment by micthiesen** [comment]
Thank you! We'll update our app next week

**Pull request merged**
