### PR TITLE
add includeCredentials param for enabling withCredentials in request

### PR DESCRIPTION
**Pull request by skashanali**
Hi, @AleeeKoi I've added that piece of code in this PR that I told you.
Kindly have a look.

### CODE REVIEW

**Comment by AleeeKoi** [comment]
Hi @skashanali !
Thank you! I'll merge it asap.

**Comment by skashanali** [comment]
Thanks, @AleeeKoi test it asap and if everything is fine please release a new version of your package with this change so that I can use that because currently, I'm stuck at this.

**Comment by AleeeKoi** [comment]
Hi @skashanali I made a little bit refactoring in your code and release the new version.
Thank you

**Comment by skashanali** [comment]
Thanks @AleeeKoi just let me know when you update the release on npm so I can go on with my use case.

**Comment by AleeeKoi** [comment]
@skashanali Already done ;)

**Comment by skashanali** [comment]
@AleeeKoi thanks a lot for your efforts :)

**Pull request closed without merging**
